model :
  embedding_size : 256

train :
  eval_every_n : 5
  report_every_n : 1
  save_every_n : 10
  keep_every_n : 10

  batch_size : 32
  eval_batch_size : 10
  num_epochs : 4


  num_eval_batches : 10
  eval_on_train : True
  eval_on_val : True

  num_workers : 4
  pin_memory : True
  log_gradients : False